# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 17:43
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='template',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager(b'sites')),
            ],
        ),
    ]
